## Лабораторная работа 2


### No1 (5 баллов)
Напишите программы, которые создают следующие массивы NumPy:

##### 1. Массив со значениями 1, 7, 13, 105. 
Посчитайте и выведите на экран размер
памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы. \
Затем загрузите его и выведите на экран.

In [1]:
import numpy as np

In [2]:

arr1 = np.array([1, 7, 13, 105])

print(arr1.nbytes)
print(arr1.dtype)

np.savetxt("arr1_1.txt", arr1, fmt="%i")

arr1.astype("int16").tofile("arr1_2")

arr2 = np.fromfile("arr1_2", dtype="int16")
arr3 = np.loadtxt("arr1_1.txt", dtype="<i")

print(arr2)
print(arr3)


16
int32
[  1   7  13 105]
[  1   7  13 105]


##### 2. Три массива: из 10 нулей, 10 единиц, 10 пятерок.

In [3]:
arr1 = np.zeros(10)
print(arr1)

arr2 = np.ones(10)
print(arr2)

arr3 = np.ones(10) * 5
print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


##### 3. Массив последовательности четных целых чисел от 30 до 70.

In [4]:
arr = np.array(range(30, 71, 2))
print(arr)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


##### 4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.

In [5]:
arr = np.linspace(5, 50, dtype="int16", num=10)
print(arr)


[ 5 10 15 20 25 30 35 40 45 50]


##### 5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.

In [6]:
arr = np.random.randint(1, 100, 27).reshape(3, 3, 3)
print(arr)


[[[35 95 11]
  [ 3 72 47]
  [82 70 25]]

 [[44 42 39]
  [ 5 18 26]
  [33 94 36]]

 [[61 42 53]
  [19 78 12]
  [59 44 13]]]


##### 6. Массив 3х4, заполненной значениями от 30 до 41.

In [7]:
arr = np.array(range(30, 42)).reshape(3, 4)
print(arr)


[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


##### 7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0

In [8]:
arr = np.zeros(10**2).reshape(10, 10)
arr[0, :] = 1    # up
arr[-1, :] = 1   # bottom
arr[0:, 0] = 1   # left
arr[0:, -1] = 1  # rigth

print(arr)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


##### 8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

In [9]:
arr = np.zeros(5**2).reshape(5, 5)
np.fill_diagonal(arr, [1, 2, 3, 4, 5])
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


##### 9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке
C нулями на
главной диагонали.

In [10]:
arr = np.zeros(4**2).reshape(4, 4)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
print(arr)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


##### 10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата.

In [11]:
arr = np.arange("2017-03", "2017-04", dtype="datetime64[D]")
print(arr)
print(arr.dtype)


['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']
datetime64[D]


### No2 (5 баллов)
Напишите следующие программы, используя подходящие функции модуля NumPy:

##### 1. Дано два массива. Получите массив, состоящий из их общих элементов.

Например, для массивов [0 10 20 40 60] и [10 30 40] ответом будет [10, 40].

In [12]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

arr3 = np.intersect1d(arr1, arr2)

print(arr1)
print(arr2)
print(arr3)


[ 0 10 20 40 60]
[10 30 40]
[10 40]


##### 2. Дан массив. Получите массив его уникальных элементов.

Исходный массив: [10 10 20 20 30 30]

Массив его уникальных элементов: [10 20 30]

Исходный массив:

[[1 1]

[2 3]]

Массив его уникальных элементов: [1 2 3]

In [13]:

arr1 = [10, 10, 20, 20, 30, 30]
arr2 = [[1, 1], [2, 3]]

for arr in [arr1, arr2]:
    print(np.unique(arr))


[10 20 30]
[1 2 3]


##### 3. Дан массив. Получите два массива: его уникальные элементы и их частоты.

Исходный массив: [10 10 20 10 20 20 20 30 30 50 40 40]

Два массива: [10 20 30 40 50], [3 4 2 2 1]

In [14]:
arr1 = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

print(*np.unique(arr1, return_counts=True))


[10 20 30 40 50] [3 4 2 2 1]


##### 4. Дан массив. Получите массив путем повторения данного.

Образец массива: [1, 2, 3, 4]

Ожидаемый результат:

 - 1 повторение
    [1, 2, 3, 4]

 - 2 повторения
    [1, 2, 3, 4, 1, 2, 3, 4]

 - 3 повторения
    [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
arr1 = np.array([1, 2, 3, 4])

arr2 = np.tile(arr1, reps=2)
arr3 = np.tile(arr1, reps=3)

print(arr1)
print(arr2)
print(arr3)


[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


##### 5. Дан массив, в котором имеются значения nan. 
Получите массив, удалив все значения nan.

Исходный массив: [200. 300. nan nan nan 700.]

После удаления значений nan: [200. 300. 700.]


Исходный массив:
[[1. 2. 3.]
[nan 0. nan]
[6. 7. nan]]

После удаления значений nan: [1. 2. 3. 0. 6. 7.]

In [16]:
arr1 = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
print(arr1)

arr2 = np.array(list(filter(lambda x: x == x, arr1)))
print(arr2)


[200. 300.  nan  nan  nan 700.]
[200. 300. 700.]


##### 6. Дан массив. Получите массив его k наименьших значений.

Оригинальный массив: [1. 7. 8. 2. 0.1 3. 15. 2.5]

Его 4 наименьших значения: [0.1 1. 2. 2.5]

In [17]:
arr1 = np.array([1., 7., 8., 2., 0.1, 3., 15., 2.5])

print(np.sort(arr1)[:4])


[0.1 1.  2.  2.5]


##### 7. Дан массив и некоторое число. Найдите ближайший по значению к числу элемент массива.

Исходный массив: [0.5 1.8 2.1 3.5 4.87 5.13 6.49]

Значение для сравнения: 3,09066280756759

Ответ: 3.5

In [18]:
arr1 = np.array([0.5, 1.8, 2.1, 3.5, 4.87, 5.13, 6.49])

compare_to = 3.09066280756759

print(arr1[np.argmin(np.abs(arr1 - compare_to))])


3.5


##### 8. Дано два массива со строками. Получите массив при помощи поэлементного объединения.

1 массив: ["Python" "PHP"]

2 массив: ["Java" "C ++"]

Результат: ["Python Java" "PHP C ++"]

In [19]:
arr1 = np.char.array(["Python", "PHP"])

arr2 = np.char.array(["Java", "C++"])

print(arr1 + " " + arr2)


['Python Java' 'PHP C++']


##### 9. Дан массив строк. Получите массив с частотой встречаемости буквы «P».

Оригинальный массив: ["Python" "PHP" "JS" " examples" "html"]

Количество "P": [1 2 0 0 0]

In [20]:
arr1 = np.char.array(["Python", "PHP", "JS", "examples", "html"])

print(np.char.count(arr1, "P"))


[1 2 0 0 0]


##### 10. Найдите корни следующих полиномов:

a. x^2 - 4х + 7

b. x^4 - 11х^3 + 9х^2 + 11х - 10

In [21]:
print(np.polynomial.Polynomial([7, -4, 1]).roots())
print(np.polynomial.Polynomial([-10, 11, 9, -11, 1]).roots())


[2.-1.73205081j 2.+1.73205081j]
[-1.+0.00000000e+00j  1.-1.32780655e-08j  1.+1.32780655e-08j
 10.+0.00000000e+00j]


### No3 (5 баллов)
Напишите программу, которая будет решать систему линейных уравнений вида:

\begin{cases}

a_{11}x + a_{12}y = b_1 \ (1) \\


a_{21}x + a_{22}y = b_2 \ (2)

\end{cases}

Коэффициенты и правую часть вводит пользователь. Программа выводит решение системы. Для нахождения решения используйте numpy.linalg.solve. 

Система не имеет решения (или имеет их бесконечно много), если определитель матрицы
коэффициентов равен 0. В этом случае необходимо выводить соответствующее сообщение.

Для нахождения определителя используйте функцию numpy.linalg.det.

In [22]:
a_coefs = [[], []]
b_coefs = []

for i in range(2):
    for j in range(2):
        a_coefs[i].append(input(f"a{i + 1}{j + 1} = "))


for i in range(2):
    b_coefs.append(input(f"b{i + 1} = "))


arr1 = np.array(a_coefs, dtype="float32")
arr2 = np.array(b_coefs, dtype="float32")

det = np.linalg.det(arr1.reshape(2, 2))

if det == 0:
    print("det = 0")
    print("no result")

else:
    print("a coefs:", arr1, sep="\n")
    print("b coefs:", arr2.reshape(2, 1), sep="\n")

    print("Result =", np.linalg.solve(arr1, arr2))


a coefs:
[[1. 2.]
 [3. 4.]]
b coefs:
[[5.]
 [6.]]
Result = [-4.   4.5]
